management:
  port: 8091

server:
  port: 8090



spring:
  data:
    mongodb:
      host: localhost
      username: giftsmart_user
      password: giftsmart_password
      database: giftsmartdb
      port: 27017


